# Navne liste
names_cwt = [
    "Gerald", "Bob", "Robert", "Antoine", "Hans", "Dick", "Ranko", "Jan", "Karl", "Ami",
    "Riki", "Eric", "Aaron", "Vic", "Moshe", "Ilya", "Dov", "Mark", "Ros", "Art", "Johannes",
    "Yuri", "Josh", "Dan", "Abdel", "Hamid", "Harry", "Chuck", "Peter", "Andy", "Sandi", "Ivo",
    "Tom", "Zlatko", "Ico", "Dado", "Bert", "Amir", "Mato", "Srdan", "Sale", "Mike", "Sven",
    "Nikola", "Braco", "Emil", "Rif", "Marin", "Manos", "John", "Steve", "Alex", "James", "Don",
    "Doug", "Marsh", "Jack", "Pat", "Dave", "Jon", "Pete", "Phil", "Joe", "Val", "Randy", "Frank",
    "Mikio", "Bud", "Ken", "Fred", "Tim", "Bill", "Chas", "Alan", "Lee", "Matt", "Jim", "Kraig",
    "Bruce", "Richard", "Duane", "Floyd", "Rick", "Dim", "Rich", "Jeff", "Darrel", "Gord", "Ralph",
    "Evan", "Vlad", "Scott", "Gary", "Howard", "Kyle", "Marcus", "Darrell", "Stu", "Venkat", "Ed",
    "Jp", "Tony", "Charles", "Joann", "Aj", "Debbie", "Dima", "Jerry", "Pavel", "Wes", "Buz", "Ned",
    "Juan", "Jason", "Ulrich", "Walt", "Stan", "Ron", "Lar", "Rob", "Kevin", "Brad", "Kurt", "Hector",
    "Ray", "Pickett", "Tj", "Paul", "Jed", "David", "Brian", "Glenn", "Lane", "Al", "Den", "Roger",
    "Kent", "Dennis", "Clark", "Donald", "Martin", "Craig", "Allen", "Rocky", "Leandra", "Earl", "Henry",
    "Hal", "Lando", "Lance", "Emma", "Jess", "Marty", "Jamie", "Greg", "Donna", "Cliff", "Ben", "Curt",
    "Jeremy", "Carl", "Barry", "Ryan", "Step", "Andrew", "Wyatt", "Amlan", "Nate", "Robie", "Olon",
    "Rowdy", "Ted", "Jaime", "Brent", "Glen", "Will", "Corliss", "Juanjo", "Bin", "Dale", "Fernando",
    "Roberto", "Carlos", "Noe", "Med", "Rey", "Oriol", "Raul", "Fil", "Men", "Jose", "Pedro", "Ulf",
    "Joao", "Jorge", "Mario", "Colin", "Gabor", "Saki", "Ugene", "Klaus", "Bernd", "Wolf", "Guenter",
    "Gunter", "Gernot", "Laft", "Juergen", "Alfred", "Stefan", "Florian", "Ekrem", "Relly", "Mitch",
    "Heijo", "Dieter", "Hardy", "Rudi", "Jo", "Simone", "Fabian", "Wilf", "Dirk", "Helmut", "Horst",
    "Oli", "Uli", "Nob", "Fritz", "Leo", "Heinz", "Uwe", "Erwin", "Gerd", "Holger", "Markus", "Chris",
    "Kolja", "Suad", "Georg", "Joerg", "Win", "Armin", "Lutz", "Seb", "Christ", "Sascha", "Stef", "Olli",
    "Sandy", "Rene", "Rainer", "Gunther", "Siggi", "Mar", "Olaf", "Max", "Toby", "Wim", "Etlev", "Hubert",
    "Loy", "Maddiin", "Erhard", "Josef", "Felix", "Mic", "Tina", "Andre", "Volkert", "Axel", "Ingo", "Wil",
    "Stephan", "Ruedi", "Karen", "Willi", "Tommy", "Franz", "Bodo", "Hannu", "Marc", "Nils", "Larry", "Champ",
    "Mew", "Vlado", "Rc", "Nermin", "Veljko", "Luis", "Oscar", "Andres", "Ignacio", "Nol", "Enio", "Francis",
    "Joan", "Manel", "Dany", "Nando", "Felipe", "Nacho", "Dani", "Josep", "Manuel", "Manfred", "Marino",
    "Franky", "Isi", "Slav", "Megan", "Declan"]
